name: Prod deployment
on:
  workflow_dispatch:

jobs:

  web:
    uses: centrifuge/website/.github/workflows/website.yml@main
    secrets: inherit
    with:
      deploy_env: production


  functions:
    uses: centrifuge/website/.github/workflows/functions.yml@main
    secrets: inherit
    with:
      deploy_env: production        
