name: Prod deployment
on:
  workflow_dispatch:

jobs:
  web:
    uses: centrifuge/website/.github/workflows/website.yml@main
    with:
      deploy_prod: true


  functions:
    uses: centrifuge/website/.github/workflows/functions.yml@main
    with:
      deploy_prod: true  