name: Trigger a deployment to prod
on:
  workflow_dispatch:

jobs:
  web:
    uses: centrifuge/website/.github/workflows/website-deploy.yml@main
    with:
      deploy_prod: true


  functions:
    uses: centrifuge/website/.github/workflows/functions-deploy.yml@main
    with:
      deploy_prod: true  