name: Build and deploy to GCloud functions
on:
  # workflow_call:
  #   inputs:
  #     env: # Used to determine the environment secrets and permissions dynamically
  #       required: true
  #       type: string
  #       default: 'preview'
  #     gcloud_project:
  #       required: true
  #       default: 'peak-vista-185616'
  #       type: string
  pull_request:
    paths: 
    - 'functions'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575 #@v3.1.0
      - name: Set .env for functions
        run: cat "CENTRIFUGE_SUBGRAPH_URL=https://graph.centrifuge.io/subgraphs/name/allow-null-maturity-date" > functions/.env
      - name: Setup Node
        uses: actions/setup-node@8c91899 #@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build:functions
      - name: Archive functions artifacts
        uses: actions/upload-artifact@v3
        with:
          name: func-dist
          retention-days: 1
          path: functions/dist
          # !dist/**/*.md

  deployment:
    needs: build
    runs-on: ubuntu-latest
    # Deployment strategy:
    # prod if deploying from main branch or preview from PRs
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    env:
      region: "europe-central2"
    steps:
      - name: download the distribution package
        uses: actions/download-artifact@v3
        with:
          name: func-dist
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}' # 'functions-firestore@peak-vista-185616.iam.gserviceaccount.com'    
      - name: Deploy to google functions
        id: gclouddeploy
        uses: google-github-actions/deploy-cloud-functions@14509ca #@v1
        with:
          name: webapi-${{ github.head_ref || github.ref_name }}
          runtime: nodejs16
          region: 'europe-west-3'
          source_dir: './'
          # project_id: '${{ env.gcloud_project }}'
          allow_unauthenticated: true
          entry_point: 'handler'
      - name: Print Gcloud functions URL
        run: echo "::notice title=Function_URL::${{ steps.gclouddeploy.outputs.url }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1 
      - name: Change function to allow_unathorized calls 
        run: |
          gcloud functions add-iam-policy-binding ${{ needs.prepare_deploy.outputs.app_name }} \
          --region=${{ env.region }} \
          --member="allUsers" --role="roles/cloudfunctions.invoker"