name: Build and Deploy website
on:
# Adding triggers other than PRs will break a lot of the code here 
#   (anything using github.event or github.ref)
  pull_request:
    path: '!functions/*'
jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: 'read'
    #   # id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/node-setup
        with:
          build_command: 'yarn build'

      - name: Archive functions artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-package
          retention-days: 1
          path: public/
  
  publish_preview:
    if: github.base_ref == 'refs/heads/main'
    environment: preview
    
    steps:
      - name: set preview URL
        run: echo "preview_url=preview{{ github.event.numbers }}.k-f.dev" >> $GITHUB_ENV

      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'

      - name: create the bucket if PR is new
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        run: |
          gsutil mb -p centrifuge-production-x gs://{{ env.preview_url }}
          gsutil iam ch allUsers:objectViewer gs://{{ env.preview_url }}
          gsutil web set -m index.html -e 404.html gs://{{ env.preview_url }}
      
      - name: delete the bucket if PR is closed
        if: github.event.action == 'closed' 
        run: gsutil rm -r gs://{{ env.preview_url }}

      - name: push to bucket otherwise
        #if:
        run: gsutil -m rsync -d -c -r ./public gs://{{ env.preview_url }}

      - name: PR comment with preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
           Preview website http://{{ env.preview_url }} refreshed with commit {{ github.sha }} 
           (HTTPS might not be available)
            
  
  publish_live_site:
    if: 'refs/heads/main'
    environment: production
    steps:
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
      - uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          number: ${{ steps.finder.outputs.pr }}
          hide_and_recreate: true
          hide_classify: 'OUTDATED'
          message: |
            <h2 align="center">IPFS Preview for ${{ github.sha }} is ready</h2>
            <p align="center">
              <a href="https://ipfs.io/ipfs/${{ steps.publish.outputs.cid }}/" target="_blank">
                <code>${{ steps.publish.outputs.cid }}</code>
                :mag_right:
              </a>
            </p>
      - name: rsync centrifuge.io site bucket
        run: gsutil -m rsync -d -c -r ./public gs://centrifuge.io



