name: Deploy website
on:
# Adding triggers other than PRs will break a lot of the code here 
#   (anything using github.event or github.ref)
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: "Deploy to prod (requires approval and wait time 120m)"
        default: false
        type: boolean
jobs:
  build-web:
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: only allow workflow_dispatch from main
        if: ${{ github.event_name == 'workflow-dispatch' }}
        run: |
          if ${{ github.ref == 'refs/heads/main' }} ; then
            echo "::error title=Bad branch selected::You can only run manual workflows from the main branch"
      - name: Set deployment vars
        uses: ./.github/actions/deploy_strategy
        id: deploy_vars
        with: 
          deploy_prod: ${{ inputs.deploy_prod }}
      
      - name: Set build env vars
        shell: bash
        working-directory: functions
        run: |
          if  ${{ github.ref == 'refs/heads/main' }} ; then
            if ${{ inputs.deploy_prod || false }}; then
              echo "GATSBY_FUNCTIONS_URL=https://${{ steps.deploy_vars.outputs.functions_region}} -{{ steps.deploy_vars.outputs.gcp_project }}.cloudfunctions.net/webapi-main" >> .env
            else
              echo "GATSBY_FUNCTIONS_URL=https://${{ steps.deploy_vars.outputs.functions_region}} -{{ steps.deploy_vars.outputs.gcp_project }}.cloudfunctions.net/webapi-main" >> .env
            fi
          else
            echo "GATSBY_FUNCTIONS_URL=https://${{ steps.deploy_vars.outputs.functions_region}} -{{ steps.deploy_vars.outputs.gcp_project }}.cloudfunctions.net/${{ needs.strategy.outputs.function_name }} >> .env
          fi

      - name: Setup Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive functions artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # @v3.1.2
        with:
          name: web-package
          retention-days: 1
          path: public/

  publish-to-gcs:
    concurrency:
      group: web-${{ github.ref }}
      cancel-in-progress: true    
    needs: build-web
    permissions:
      contents: read
      id-token: write 
      pull-requests: write
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_prod && 'production' || 'development' }}
    steps:
      - name: Set deployment vars
        uses: ./.github/actions/deploy_strategy
        id: deploy_vars
        with: 
          deploy_prod: ${{ inputs.deploy_prod == 'true' }}    

      - name: download webpack
        id: download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # @v3.0.2
        with:
          name: web-package
          path: webpack

      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1' 

      - name: try to create bucket
        id: create_bucket
        continue-on-error: true
        run: |
          gsutil mb gs://${{ steps.deploy_vars.outputs.bucket_url }}
          gsutil iam ch allUsers:objectViewer gs://${{ steps.deploy_vars.outputs.bucket_url }}
          gsutil web set -m index.html -e 404.html gs://${{ steps.deploy_vars.outputs.bucket_url }}

      - name: push to bucket
        id: push
        run: gsutil -m rsync -d -c -r ${{steps.download.outputs.download-path}} gs://${{ steps.deploy_vars.outputs.bucket_url }}

      - name: PR comment with preview URL
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && steps.push.outcome == 'success'
        with:
          message: |
            Deployed webiste in Google Cloud
            URL: http://${{ steps.deploy_vars.outputs.bucket_url }}
            Commit #: ${{ github.event.pull_request.head.sha }}   
      - run: echo "::notice title=web_url::${{ steps.deploy_vars.outputs.bucket_url }}"     

  notify_slack:
    needs: publish-to-gcs
    runs-on: ubuntu-latest
    if: inputs.deploy_prod
    steps:
        - name: Slack on prod publishing
          uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: "centrifuge.io website deployed"

  check_function_exists:
    permissions:
      contents: read
      id-token: write 
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_prod && 'production' || 'development' }}
    steps:   
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
          # create_credentials_file: false
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1' 

      - name: check function
       # Deploy function for every website PR deployed for previews
        id: check_function
        shell: bash
        run: |
          if gcloud functions describe --region europe-central2 webapi-${{ github.head_ref || github.ref_name }} 2> /dev/null; then
            echo "deploy=false" >> $GITHUB_OUTPUT
          else
            echo "deploy=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true    
    outputs:
      deploy_function: ${{ steps.check_function.outputs.deploy }} 

  
  deploy_pr:
    needs: check_function_exists
    if: ${{needs.check_function_exists.outputs.deploy_function == 'true' &&  github.event_name == 'pull_request' }}
    uses: ./.github/workflows/functions-deploy.yml
    secrets: inherit
    with:
      deploy_prod: false

  deploy_prod:
    if: github.event.inputs.deploy_prod
    uses: ./.github/workflows/functions-deploy.yml
    secrets: inherit        
    with:
      deploy_prod: true
